In [1]:
import torch
from torch import optim, nn
from functools import partial
from tqdm import tqdm
from torchinfo import summary
from torch.utils.data import Dataset, DataLoader
import wandb 
from collections import defaultdict
import numpy as np

In [2]:
import sys
from pathlib import Path

# Add the 'src' folder to sys.path
sys.path.append(str(Path().resolve().parent / "src"))

from initialize import *
from classes import *
from train import *
from data_proc import *

In [3]:
str(Path().resolve().parent / "src")

'/nfs/scistore23/chlgrp/avolkova/rotation1/pipeline/src'

In [16]:
loaders = create_loaders(buffer_size=1000)

100%|██████████| 10/10 [00:00<00:00, 607.08it/s]


In [17]:
for task_id in range(10):
    print(len(loaders["val"][task_id]))
    print(len(loaders["train"][task_id]))

4
36
4
43
4
43
4
43
4
43
4
43
4
43
4
43
4
43
4
43


In [18]:

for task_id in range(10):
    val_label_num = np.zeros(100, dtype=int)
    train_label_num = np.zeros(100, dtype=int)
    
    for data, label in loaders["val"][task_id]:
        for l in label:
            val_label_num[l] += 1    
            
    for data, label in loaders["train"][task_id]:
        for l in label:
            train_label_num[l] += 1

    print(task_id, val_label_num.nonzero())
    print(train_label_num[:10*task_id].sum(), train_label_num)

0 (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)
0 [450 450 450 450 450 450 450 450 450 450   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0]
1 (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)
1000 [100 100 100 100 100 100 100 100 100 100 450 450 450 450 450 450 450 450
 450 450   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0]
2 (array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),)
1000 [ 50  50  50  50  50  50 

In [14]:
for task_id in range(10):
    test_label_num = np.zeros(100, dtype=int)
    
    for data, label in loaders["test"][task_id]:
        for l in label:
            test_label_num[l] += 1    
            
    print(task_id, test_label_num.nonzero())

0 (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)
1 (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)
2 (array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),)
3 (array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),)
4 (array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)
5 (array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),)
6 (array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]),)
7 (array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),)
8 (array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),)
9 (array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)


In [8]:
torch.randperm(100)

tensor([96, 78, 95, 77, 28, 97, 69, 64, 14, 12, 88, 86, 65, 43, 84, 70, 31, 98,
        52, 24, 38, 66, 21, 23, 40, 62, 60, 33,  8, 17, 67, 20, 11, 91, 48, 63,
        93, 99, 10, 45, 73, 59, 82, 34, 49,  2, 90,  7,  3, 46, 87, 76, 26, 56,
        89, 54, 35, 94, 55, 58,  0, 25, 29, 61, 27, 85, 16, 71, 22, 19, 41, 42,
        30, 57, 13, 37, 74,  1, 50, 18, 39, 44, 53, 47, 36, 51, 79, 83, 68, 72,
        75,  6, 81,  5, 92, 32, 80,  4,  9, 15])

In [9]:
optimizer = optim.AdamW(nn.Linear(1, 1).parameters(), lr=1e-6)

optimizer.param_groups[0]["lr"] 

1e-06

In [10]:
np.array([1, 2, 3]) * 2

array([2, 4, 6])

In [11]:
torch.tensor(range(1, 6), dtype=int) * 3 * 10


tensor([ 30,  60,  90, 120, 150])

In [12]:
range(7)

range(0, 7)

In [13]:
a = [4,5]
a.append(4)
a

[4, 5, 4]