In [190]:
import torch
from torch import optim, nn
from functools import partial


In [157]:
from initialize import *

In [252]:
model = nn.Linear(10, 5)

optimizer = optim.SGD(model.parameters(), lr=1)
criterion = nn.CrossEntropyLoss()

In [253]:
old = model.weight.detach().clone()
old

tensor([[-0.1922, -0.0244,  0.1427, -0.1275, -0.1680, -0.1448,  0.3027, -0.0618,
          0.0321,  0.2736],
        [-0.2548,  0.1016,  0.1874,  0.1151,  0.0753, -0.1704, -0.1242, -0.0014,
         -0.0504,  0.2900],
        [-0.2566,  0.2901,  0.2249, -0.0976, -0.2419, -0.1379, -0.0907, -0.2692,
          0.2005, -0.2647],
        [-0.2032, -0.1043,  0.0273, -0.2816, -0.3070, -0.0194,  0.1192, -0.2898,
         -0.0006,  0.1752],
        [ 0.3029,  0.2622,  0.1841, -0.1187,  0.0830,  0.1624, -0.2479, -0.1528,
          0.2537,  0.0968]])

In [254]:
model.weight.grad

In [255]:
def hook(grad, cond):
    print("hook")
    grad[:cond[0]] = 0
    grad[cond[1]:] = 0
    return grad


target_sep = [(0,1), (2,3)]

h = model.weight.register_hook(partial(hook, cond=target_sep[0]))

In [256]:
optimizer.zero_grad()
loss = criterion(model(torch.rand((1, 10))), torch.tensor([2], dtype=int))
model.train()
loss.backward()
optimizer.step()

hook


In [257]:
(model.weight - old).mean(axis=-1)

tensor([-0.1003,  0.0000,  0.0000,  0.0000,  0.0000], grad_fn=<MeanBackward1>)

In [258]:
model.weight.grad

tensor([[0.1053, 0.0097, 0.1441, 0.0339, 0.1870, 0.1779, 0.1774, 0.0491, 0.0293,
         0.0894],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [259]:
model.weight

Parameter containing:
tensor([[-0.2975, -0.0341, -0.0014, -0.1613, -0.3550, -0.3228,  0.1253, -0.1109,
          0.0028,  0.1842],
        [-0.2548,  0.1016,  0.1874,  0.1151,  0.0753, -0.1704, -0.1242, -0.0014,
         -0.0504,  0.2900],
        [-0.2566,  0.2901,  0.2249, -0.0976, -0.2419, -0.1379, -0.0907, -0.2692,
          0.2005, -0.2647],
        [-0.2032, -0.1043,  0.0273, -0.2816, -0.3070, -0.0194,  0.1192, -0.2898,
         -0.0006,  0.1752],
        [ 0.3029,  0.2622,  0.1841, -0.1187,  0.0830,  0.1624, -0.2479, -0.1528,
          0.2537,  0.0968]], requires_grad=True)

In [260]:
old

tensor([[-0.1922, -0.0244,  0.1427, -0.1275, -0.1680, -0.1448,  0.3027, -0.0618,
          0.0321,  0.2736],
        [-0.2548,  0.1016,  0.1874,  0.1151,  0.0753, -0.1704, -0.1242, -0.0014,
         -0.0504,  0.2900],
        [-0.2566,  0.2901,  0.2249, -0.0976, -0.2419, -0.1379, -0.0907, -0.2692,
          0.2005, -0.2647],
        [-0.2032, -0.1043,  0.0273, -0.2816, -0.3070, -0.0194,  0.1192, -0.2898,
         -0.0006,  0.1752],
        [ 0.3029,  0.2622,  0.1841, -0.1187,  0.0830,  0.1624, -0.2479, -0.1528,
          0.2537,  0.0968]])

In [236]:
num_tasks = 10
set_size = 100 // num_tasks
target_sep = [(i*set_size, (i+1)*set_size) for i in range(num_tasks)]
target_sep[-1] = (target_sep[-1][0], 100)

In [237]:
target_sep

[(0, 10),
 (10, 20),
 (20, 30),
 (30, 40),
 (40, 50),
 (50, 60),
 (60, 70),
 (70, 80),
 (80, 90),
 (90, 100)]

In [240]:
a = torch.rand((4, 5))
a

tensor([[0.2727, 0.9049, 0.7966, 0.5810, 0.3650],
        [0.7375, 0.4366, 0.7186, 0.0105, 0.7604],
        [0.7147, 0.4369, 0.4764, 0.1091, 0.3966],
        [0.7021, 0.5749, 0.9472, 0.8856, 0.3974]])

In [244]:
a[0:1, 4:5]

tensor([[0.3650]])

In [265]:
import numpy as np

0.95**40

0.12851215656510312